#!/bin/bash
set -e

mix test
MIX_ENV=prod mix release prod --overwrite --force

if [[ "$1" == "-r" ]]; then
  _build/prod/rel/prod/bin/prod start 2> log_file 1> log_file &
  echo "Running with pid $!"
fi

if [[ "$1" == "-d" ]]; then
  tar -czvf release.tar _build/prod/rel/prod
  scp release.tar run_on_prod .secrets.env berners@dave:~/
fi
