#!/bin/bash

sudo echo "a prompt for sudo"
_build/prod/rel/prod/bin/prod stop > /dev/null 2>&1
tar -xvf release.tar

export PHX_SERVER="true"
#export RELEASE_NAME="cool_release"
export SECRET_KEY_BASE="GtNMPplTGjhEVVBu0/dagB9xeiJvqApKExtqgdacvgWLNibJTyirlD5gMLN+i1/C"
export DATABASE_URL="postgres://postgres:postgres@localhost:5432/dave_dev"
export HTTP_PORT=80
export HTTPS_PORT=443
export USE_THE_DB="false"
export SSL_CERT_PATH="/etc/letsencrypt/live/berners.dev/fullchain.pem"
export SSL_KEY_PATH="/etc/letsencrypt/live/berners.dev/privkey.pem"
export APP_HOST="berners.dev"
export PHX_HOST=$APP_HOST

sudo --preserve-env _build/prod/rel/prod/bin/prod start >> log_file 2>&1 &
echo $?
