#!/bin/bash

sudo echo "a prompt for sudo"
#_build/prod/rel/prod/bin/prod stop > /dev/null 2>&1
_build/prod/rel/prod/bin/prod stop > /dev/null 2>&1
tar -xvf release.tar

export APP_HOST="dave"
export PHX_SERVER="true"
export RELEASE_NAME="cool_release"
export PHX_HOST=$APP_HOST
export SECRET_KEY_BASE="GtNMPplTGjhEVVBu0/dagB9xeiJvqApKExtqgdacvgWLNibJTyirlD5gMLN+i1/C"
export DATABASE_URL="postgres://postgres:postgres@localhost:5432/dave_dev"
export PORT=80
export USE_THE_DB="false"

sudo --preserve-env _build/prod/rel/prod/bin/prod start &
