#!/bin/bash

set -a
. .secrets.env
set +a

export PHX_SERVER="true"
export DATABASE_URL="postgres://$DB_USER:$DB_PASSWORD@localhost:5432/dave"
export HTTP_PORT=80
export HTTPS_PORT=443

sudo echo "a prompt for sudo" > /dev/null
echo $?
_build/prod/rel/prod/bin/prod stop
tar -xvf release.tar

sudo --preserve-env _build/prod/rel/prod/bin/prod eval "Dave.Release.migrate"
sudo --preserve-env _build/prod/rel/prod/bin/prod start >> log_file 2>&1 &
